package view;

import control.GerenciadorDeInterface;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author wanes
 */
public class DlgConsultarCliente extends javax.swing.JDialog {

    
    private GerenciadorDeInterface inter;
    private JTable tabelaCliente;
    
    /**
     * Creates new form DlgConsultarCliente
     * @param parent
     * @param modal
     * @param gInterface
     */
    public DlgConsultarCliente(java.awt.Frame parent, boolean modal, GerenciadorDeInterface gInterface) {
        super(parent, modal);
        this.inter = gInterface;
        tabelaCliente = new JTable();
        getContentPane().add(new JScrollPane(tabelaCliente));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panConsultarCliente2 = new javax.swing.JPanel();
        panConsultarCliente = new javax.swing.JPanel();
        labDescricaoConsultarCliente = new javax.swing.JLabel();
        fieldDescricaoConsultarCliente = new javax.swing.JTextField();
        btPesquisarConsultarCliente = new javax.swing.JButton();
        scrolConsultarCliente = new javax.swing.JScrollPane();
        tableConsultarCliente = new javax.swing.JTable();
        btVoltarConsultarCliente = new javax.swing.JButton();
        btCancelarConsultarCliente = new javax.swing.JButton();
        btEditarConsultarCliente = new javax.swing.JButton();
        btSalvarConsultarCliente = new javax.swing.JButton();
        btExcluirConsultarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panConsultarCliente2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panConsultarCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Cliente"));
        panConsultarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labDescricaoConsultarCliente.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labDescricaoConsultarCliente.setText("Descrição:");
        panConsultarCliente.add(labDescricaoConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        fieldDescricaoConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDescricaoConsultarClienteActionPerformed(evt);
            }
        });
        panConsultarCliente.add(fieldDescricaoConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 280, -1));
        panConsultarCliente.add(btPesquisarConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 40, 20));

        tableConsultarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome", "E-mail", "CPF", "Celular", "Cidade", "UF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrolConsultarCliente.setViewportView(tableConsultarCliente);

        panConsultarCliente.add(scrolConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 47, 440, 160));

        panConsultarCliente2.add(panConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 470, 220));

        btVoltarConsultarCliente.setText("Voltar");
        btVoltarConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarConsultarClienteActionPerformed(evt);
            }
        });
        panConsultarCliente2.add(btVoltarConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 20));

        btCancelarConsultarCliente.setText("Cancelar");
        btCancelarConsultarCliente.setEnabled(false);
        btCancelarConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarConsultarClienteActionPerformed(evt);
            }
        });
        panConsultarCliente2.add(btCancelarConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 110, 30));

        btEditarConsultarCliente.setText("Editar");
        panConsultarCliente2.add(btEditarConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 110, 30));

        btSalvarConsultarCliente.setText("Salvar");
        btSalvarConsultarCliente.setEnabled(false);
        panConsultarCliente2.add(btSalvarConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 110, 30));

        btExcluirConsultarCliente.setText("Excluir");
        panConsultarCliente2.add(btExcluirConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 110, 30));

        getContentPane().add(panConsultarCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 570, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldDescricaoConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDescricaoConsultarClienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_fieldDescricaoConsultarClienteActionPerformed

    private void btVoltarConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarConsultarClienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        try {
            //--Abre o DlgMenu
            inter.abrirJanelaDlgMenu();
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(DlgConsultarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btVoltarConsultarClienteActionPerformed

    private void btCancelarConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarConsultarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelarConsultarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarConsultarCliente;
    private javax.swing.JButton btEditarConsultarCliente;
    private javax.swing.JButton btExcluirConsultarCliente;
    private javax.swing.JButton btPesquisarConsultarCliente;
    private javax.swing.JButton btSalvarConsultarCliente;
    private javax.swing.JButton btVoltarConsultarCliente;
    private javax.swing.JTextField fieldDescricaoConsultarCliente;
    private javax.swing.JLabel labDescricaoConsultarCliente;
    private javax.swing.JPanel panConsultarCliente;
    private javax.swing.JPanel panConsultarCliente2;
    private javax.swing.JScrollPane scrolConsultarCliente;
    private javax.swing.JTable tableConsultarCliente;
    // End of variables declaration//GEN-END:variables
}
