package view;


import control.FornecedorAbstractTableModel;
import control.GerenciadorDeInterface;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Fornecedor;
import org.hibernate.HibernateException;

/**
 *
 * @author wanes
 */
public class DlgConsultarFornecedor extends javax.swing.JDialog {

    
    private GerenciadorDeInterface gInterface;     
    private FornecedorAbstractTableModel fornecedorTableModel;
    private Fornecedor fornecedorSelecionado = null;
    
    /**
     * Creates new form DlgConsultarFornecedor
     * @param parent
     * @param modal
     * @param gInterface
     */
    public DlgConsultarFornecedor(java.awt.Frame parent, boolean modal, GerenciadorDeInterface gInterface) {
        super(parent, modal);
        this.gInterface = gInterface;
        initComponents();        
        
        fornecedorTableModel = new FornecedorAbstractTableModel();
        tableConsultarFornecedor.setModel(fornecedorTableModel);
    }
     
     
    public Fornecedor getFornecedorSelecionado(){
        return fornecedorSelecionado;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panConsultarFornecedor2 = new javax.swing.JPanel();
        panConsultarFornecedor = new javax.swing.JPanel();
        labDescricaoConsultarFornecedor = new javax.swing.JLabel();
        fieldDescricaoConsultarFornecedor = new javax.swing.JTextField();
        btPesquisarConsultarFornecedor = new javax.swing.JButton();
        scrolConsultarCliente = new javax.swing.JScrollPane();
        tableConsultarFornecedor = new javax.swing.JTable();
        btVoltarConsultarFornecedor = new javax.swing.JButton();
        btCancelarConsultarFornecedor = new javax.swing.JButton();
        btEditarConsultarFornecedor = new javax.swing.JButton();
        btSalvarConsultarFornecedor = new javax.swing.JButton();
        btExcluirConsultarFornecedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panConsultarFornecedor2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panConsultarFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Fornecedor"));
        panConsultarFornecedor.setToolTipText("");
        panConsultarFornecedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labDescricaoConsultarFornecedor.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labDescricaoConsultarFornecedor.setText("Descrição:");
        panConsultarFornecedor.add(labDescricaoConsultarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        fieldDescricaoConsultarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDescricaoConsultarFornecedorActionPerformed(evt);
            }
        });
        panConsultarFornecedor.add(fieldDescricaoConsultarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 280, -1));

        btPesquisarConsultarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarConsultarFornecedorActionPerformed(evt);
            }
        });
        panConsultarFornecedor.add(btPesquisarConsultarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 40, 20));

        tableConsultarFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "E-mail", "CNPJ", "Celular", "Cidade", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrolConsultarCliente.setViewportView(tableConsultarFornecedor);

        panConsultarFornecedor.add(scrolConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 47, 440, 160));

        panConsultarFornecedor2.add(panConsultarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 470, 220));

        btVoltarConsultarFornecedor.setText("Voltar");
        btVoltarConsultarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarConsultarFornecedorActionPerformed(evt);
            }
        });
        panConsultarFornecedor2.add(btVoltarConsultarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 20));

        btCancelarConsultarFornecedor.setText("Cancelar");
        btCancelarConsultarFornecedor.setEnabled(false);
        btCancelarConsultarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarConsultarFornecedorActionPerformed(evt);
            }
        });
        panConsultarFornecedor2.add(btCancelarConsultarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 110, 30));

        btEditarConsultarFornecedor.setText("Editar");
        panConsultarFornecedor2.add(btEditarConsultarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 110, 30));

        btSalvarConsultarFornecedor.setText("Salvar");
        btSalvarConsultarFornecedor.setEnabled(false);
        panConsultarFornecedor2.add(btSalvarConsultarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 110, 30));

        btExcluirConsultarFornecedor.setText("Excluir");
        panConsultarFornecedor2.add(btExcluirConsultarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 110, 30));

        getContentPane().add(panConsultarFornecedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 570, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldDescricaoConsultarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDescricaoConsultarFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDescricaoConsultarFornecedorActionPerformed

    private void btVoltarConsultarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarConsultarFornecedorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        try {
            /*Abre o DlgMenu*/
            gInterface.abrirJanelaDlgMenu();
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(DlgConsultarFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btVoltarConsultarFornecedorActionPerformed

    private void btCancelarConsultarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarConsultarFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelarConsultarFornecedorActionPerformed

    private void btPesquisarConsultarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarConsultarFornecedorActionPerformed
        String pesq = fieldDescricaoConsultarFornecedor.getText();
        List lista;
        
        try {
            lista = gInterface.getDominio().pesquisarFornecedor(pesq);
            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Fornecedor não encontrado", "Pesquisar Fornecedor", JOptionPane.INFORMATION_MESSAGE);
            }
            fornecedorTableModel.setLista((List<Fornecedor>) lista);
        } catch (ClassNotFoundException | HibernateException ex) {
            ex.printStackTrace(); // Log completo da exceção
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar: " + ex.getMessage(), "Pesquisar Fornecedor", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            ex.printStackTrace(); // Log completo da exceção
            Logger.getLogger(DlgConsultarFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btPesquisarConsultarFornecedorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarConsultarFornecedor;
    private javax.swing.JButton btEditarConsultarFornecedor;
    private javax.swing.JButton btExcluirConsultarFornecedor;
    private javax.swing.JButton btPesquisarConsultarFornecedor;
    private javax.swing.JButton btSalvarConsultarFornecedor;
    private javax.swing.JButton btVoltarConsultarFornecedor;
    private javax.swing.JTextField fieldDescricaoConsultarFornecedor;
    private javax.swing.JLabel labDescricaoConsultarFornecedor;
    private javax.swing.JPanel panConsultarFornecedor;
    private javax.swing.JPanel panConsultarFornecedor2;
    private javax.swing.JScrollPane scrolConsultarCliente;
    private javax.swing.JTable tableConsultarFornecedor;
    // End of variables declaration//GEN-END:variables
}
