package view;

import control.GerenciadorDeInterface;
import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import model.Cliente;
import model.Fornecedor;
import model.Produto;
import model.Venda;
import org.hibernate.HibernateException;

/**
 *
 * @author wanes
 */
public class DlgMenu extends javax.swing.JDialog {
    
    private DlgConsultarCliente dlgCliente = null;
    private DlgConsultarFornecedor dlgFornecedor = null;

    private GerenciadorDeInterface gInterface;    
    
    /**
     * Creates new form DlgMenu
     * @param parent
     * @param modal
     * @param gInterface
     */
    public DlgMenu(java.awt.Frame parent, boolean modal, GerenciadorDeInterface gInterface) {
        super(parent, modal);
        this.gInterface = gInterface;
        this.dlgFornecedor = new DlgConsultarFornecedor(parent, modal, gInterface);
        this.dlgCliente = new DlgConsultarCliente(parent, modal, gInterface);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        tpanMenu = new javax.swing.JTabbedPane();
        panFornecedor = new javax.swing.JPanel();
        btConsultarFornecedor = new javax.swing.JButton();
        btCancelarFornecedor = new javax.swing.JButton();
        btSalvarFornecedor = new javax.swing.JButton();
        panDadosPessoaisFornecedor = new javax.swing.JPanel();
        labNomeFornecedor = new javax.swing.JLabel();
        fieldNomeFornecedor = new javax.swing.JTextField();
        labEmailFornecedor = new javax.swing.JLabel();
        fieldEmailFornecedor = new javax.swing.JTextField();
        labCNPJFornecedor = new javax.swing.JLabel();
        formatCNPJFornecedor = new javax.swing.JFormattedTextField();
        labCelularFornecedor = new javax.swing.JLabel();
        formatCelularFornecedor = new javax.swing.JFormattedTextField();
        panEnderecoFornecedor = new javax.swing.JPanel();
        labCEPFornecedor = new javax.swing.JLabel();
        formatCEPFornecedor = new javax.swing.JFormattedTextField();
        labNFornecedor = new javax.swing.JLabel();
        formatNFornecedor = new javax.swing.JFormattedTextField();
        labCidadeFornecedor = new javax.swing.JLabel();
        fieldCidadeFornecedor = new javax.swing.JTextField();
        cbEstadoFornecedor = new javax.swing.JComboBox<>();
        labBairroFornecedor = new javax.swing.JLabel();
        labComplementoFornecedor = new javax.swing.JLabel();
        labRuaFornecedor = new javax.swing.JLabel();
        fieldRuaFornecedor = new javax.swing.JTextField();
        fieldComplementoFornecedor = new javax.swing.JTextField();
        fieldBairroFornecedor = new javax.swing.JTextField();
        panClientes = new javax.swing.JPanel();
        btSalvarCliente = new javax.swing.JButton();
        btCancelarCliente = new javax.swing.JButton();
        btConsultarCliente = new javax.swing.JButton();
        panDadosPessoaisCliente = new javax.swing.JPanel();
        labNomeCliente = new javax.swing.JLabel();
        fieldNomeCliente = new javax.swing.JTextField();
        labEmailCliente = new javax.swing.JLabel();
        fieldEmailCliente = new javax.swing.JTextField();
        labCPFCliente = new javax.swing.JLabel();
        formatCPFCliente = new javax.swing.JFormattedTextField();
        labCelularCliente = new javax.swing.JLabel();
        formatCelularCliente = new javax.swing.JFormattedTextField();
        panEnderecoCliente = new javax.swing.JPanel();
        labCEPCliente = new javax.swing.JLabel();
        formatCEPCliente = new javax.swing.JFormattedTextField();
        labNCliente = new javax.swing.JLabel();
        formatNCliente = new javax.swing.JFormattedTextField();
        labCidadeCliente = new javax.swing.JLabel();
        fieldCidadeCliente = new javax.swing.JTextField();
        cbEstadoCliente = new javax.swing.JComboBox<>();
        labBairroCliente = new javax.swing.JLabel();
        labComplementoCliente = new javax.swing.JLabel();
        labRuaCliente = new javax.swing.JLabel();
        fieldRuaCliente = new javax.swing.JTextField();
        fieldComplementoCliente = new javax.swing.JTextField();
        fieldBairroCliente = new javax.swing.JTextField();
        panProduto = new javax.swing.JTabbedPane();
        panConsultarProduto = new javax.swing.JPanel();
        btEditarConsultarProduto = new javax.swing.JButton();
        btSalvarConsultarProduto = new javax.swing.JButton();
        btCancelarConsultarProduto1 = new javax.swing.JButton();
        btExcluirConsultarProduto = new javax.swing.JButton();
        panConsultarProdutos = new javax.swing.JPanel();
        labDescricaoConsultarProduto = new javax.swing.JLabel();
        fieldDescricaoConsultarProduto = new javax.swing.JTextField();
        btPesquisarConsultarProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableConsultarProduto = new javax.swing.JTable();
        panControleEstoque = new javax.swing.JPanel();
        labDescricaoControle = new javax.swing.JLabel();
        fieldQtAtualControleEstoque = new javax.swing.JTextField();
        btAdicionarControleEstoque = new javax.swing.JButton();
        labQtAtualControleEstoque = new javax.swing.JLabel();
        fieldDescricaoControleEstoque = new javax.swing.JTextField();
        labAdicionarQuantidade = new javax.swing.JLabel();
        fieldQtControleEstoque = new javax.swing.JTextField();
        btBuscarProdutoControleEstoque = new javax.swing.JButton();
        panListaProdutos = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableControleProduto = new javax.swing.JTable();
        panCadastrarProduto = new javax.swing.JPanel();
        btCancelarCadastrarProduto = new javax.swing.JButton();
        btSalvarCadastrarProduto = new javax.swing.JButton();
        panCadastrarProdutos = new javax.swing.JPanel();
        labFornecedorProduto = new javax.swing.JLabel();
        labQtEstoqueProduto = new javax.swing.JLabel();
        labDescricaoProduto = new javax.swing.JLabel();
        labNomeProduto = new javax.swing.JLabel();
        labCodigoProduto = new javax.swing.JLabel();
        fieldCodigoProduto1 = new javax.swing.JTextField();
        cbUnidadeMedidaProduto = new javax.swing.JComboBox<>();
        formatTamProduto = new javax.swing.JFormattedTextField();
        labTamProduto = new javax.swing.JLabel();
        fieldNomeProduto = new javax.swing.JTextField();
        fieldDescricaoProduto = new javax.swing.JTextField();
        formatQtEstoqueProduto = new javax.swing.JFormattedTextField();
        labPrecoProduto = new javax.swing.JLabel();
        formatPrecoProduto = new javax.swing.JFormattedTextField();
        cbCategoriaProduto = new javax.swing.JComboBox<>();
        cbFornecedorProduto = new javax.swing.JComboBox<>();
        panVenda = new javax.swing.JTabbedPane();
        panPontoVenda = new javax.swing.JPanel();
        btAdicionarProdutoVenda = new javax.swing.JButton();
        btLimparDadosVenda = new javax.swing.JButton();
        panDadosCliente = new javax.swing.JPanel();
        labCPFClienteVenda = new javax.swing.JLabel();
        formatCPFClienteVenda = new javax.swing.JFormattedTextField();
        labNomeClienteVenda = new javax.swing.JLabel();
        fieldNomeClienteVenda = new javax.swing.JTextField();
        btBuscarClienteVenda = new javax.swing.JToggleButton();
        panDadosProduto = new javax.swing.JPanel();
        labCodigoProdutoVenda = new javax.swing.JLabel();
        fieldCodigoProdutoVenda = new javax.swing.JTextField();
        btBuscarProdutoVenda = new javax.swing.JToggleButton();
        labNomeProdutoVenda = new javax.swing.JLabel();
        fieldNomeProdutoVenda = new javax.swing.JTextField();
        labEstoqueProdutoVenda = new javax.swing.JLabel();
        formatEstoqueProdutoVenda = new javax.swing.JFormattedTextField();
        labQtProdutoVenda = new javax.swing.JLabel();
        formatQtProdutoVenda = new javax.swing.JFormattedTextField();
        formatDescontoProdutoVenda = new javax.swing.JFormattedTextField();
        labDescontoProdutoVenda = new javax.swing.JLabel();
        formatPrecoProdutoVenda = new javax.swing.JFormattedTextField();
        labPrecoProdutoVenda = new javax.swing.JLabel();
        panCarrinho = new javax.swing.JPanel();
        formatTotalCarrinhoVenda = new javax.swing.JFormattedTextField();
        labTotalCarrinhoVenda = new javax.swing.JLabel();
        btPagamentoCarrinhoVenda = new javax.swing.JButton();
        fieldDataCarrinhoVenda = new javax.swing.JTextField();
        btCancelarCarrinhoVenda = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableCarrinhoVenda = new javax.swing.JTable();
        labDataCarrinhoVenda = new javax.swing.JLabel();
        panPosicaoDiaVenda = new javax.swing.JPanel();
        panPosicaoDia = new javax.swing.JPanel();
        labTotalPosicaoVenda = new javax.swing.JLabel();
        formatDataPosicao = new javax.swing.JFormattedTextField();
        btBuscarPosicaoVenda = new javax.swing.JButton();
        fieldTotalPosicaoVenda = new javax.swing.JTextField();
        labDataPosicaoVenda = new javax.swing.JLabel();
        panHistoricoVenda = new javax.swing.JPanel();
        panHistorico = new javax.swing.JPanel();
        labDataFimVenda = new javax.swing.JLabel();
        labDataInicioVenda = new javax.swing.JLabel();
        formatDataInicioVenda = new javax.swing.JFormattedTextField();
        formatDataFimVenda = new javax.swing.JFormattedTextField();
        btBuscarHistoricoVenda = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableHistoricoVenda = new javax.swing.JTable();
        panConfiguracao = new javax.swing.JPanel();
        panSair = new javax.swing.JPanel();
        btEncerrar = new javax.swing.JToggleButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tpanMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tpanMenu.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N

        panFornecedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panFornecedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btConsultarFornecedor.setText("Consultar");
        btConsultarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarFornecedorActionPerformed(evt);
            }
        });
        panFornecedor.add(btConsultarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, 30));

        btCancelarFornecedor.setText("Cancelar");
        btCancelarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarFornecedorActionPerformed(evt);
            }
        });
        panFornecedor.add(btCancelarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 110, 30));

        btSalvarFornecedor.setText("Salvar");
        btSalvarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarFornecedorActionPerformed(evt);
            }
        });
        panFornecedor.add(btSalvarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 110, 30));

        panDadosPessoaisFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));
        panDadosPessoaisFornecedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labNomeFornecedor.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labNomeFornecedor.setText("Nome:");
        panDadosPessoaisFornecedor.add(labNomeFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        panDadosPessoaisFornecedor.add(fieldNomeFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 280, -1));

        labEmailFornecedor.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labEmailFornecedor.setText("E-mail:");
        panDadosPessoaisFornecedor.add(labEmailFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        panDadosPessoaisFornecedor.add(fieldEmailFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 280, -1));

        labCNPJFornecedor.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labCNPJFornecedor.setText("CNPJ:");
        panDadosPessoaisFornecedor.add(labCNPJFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        try {
            formatCNPJFornecedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        panDadosPessoaisFornecedor.add(formatCNPJFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 90, -1));

        labCelularFornecedor.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labCelularFornecedor.setText("Celular:");
        panDadosPessoaisFornecedor.add(labCelularFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        try {
            formatCelularFornecedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        panDadosPessoaisFornecedor.add(formatCelularFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 90, -1));

        panFornecedor.add(panDadosPessoaisFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 360, 210));
        panDadosPessoaisFornecedor.getAccessibleContext().setAccessibleDescription("");

        panEnderecoFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));
        panEnderecoFornecedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labCEPFornecedor.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labCEPFornecedor.setText("CEP:");
        panEnderecoFornecedor.add(labCEPFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        try {
            formatCEPFornecedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        panEnderecoFornecedor.add(formatCEPFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 80, -1));

        labNFornecedor.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labNFornecedor.setText("Nº:");
        panEnderecoFornecedor.add(labNFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        formatNFornecedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        panEnderecoFornecedor.add(formatNFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 30, -1));

        labCidadeFornecedor.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labCidadeFornecedor.setText("Cidade:");
        panEnderecoFornecedor.add(labCidadeFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        panEnderecoFornecedor.add(fieldCidadeFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 80, -1));

        cbEstadoFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UF", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        panEnderecoFornecedor.add(cbEstadoFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 50, -1));

        labBairroFornecedor.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labBairroFornecedor.setText("Bairro:");
        panEnderecoFornecedor.add(labBairroFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        labComplementoFornecedor.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labComplementoFornecedor.setText("Complemento:");
        panEnderecoFornecedor.add(labComplementoFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        labRuaFornecedor.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labRuaFornecedor.setText("Rua:");
        panEnderecoFornecedor.add(labRuaFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        panEnderecoFornecedor.add(fieldRuaFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 160, -1));
        panEnderecoFornecedor.add(fieldComplementoFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 100, -1));
        panEnderecoFornecedor.add(fieldBairroFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 150, -1));

        panFornecedor.add(panEnderecoFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 230, 210));

        tpanMenu.addTab("Fornecedores", panFornecedor);

        panClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSalvarCliente.setText("Salvar");
        btSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarClienteActionPerformed(evt);
            }
        });
        panClientes.add(btSalvarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 110, 30));

        btCancelarCliente.setText("Cancelar");
        btCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarClienteActionPerformed(evt);
            }
        });
        panClientes.add(btCancelarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 110, 30));

        btConsultarCliente.setText("Consultar");
        btConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarClienteActionPerformed(evt);
            }
        });
        panClientes.add(btConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, 30));

        panDadosPessoaisCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));
        panDadosPessoaisCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labNomeCliente.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labNomeCliente.setText("Nome:");
        panDadosPessoaisCliente.add(labNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        panDadosPessoaisCliente.add(fieldNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 280, -1));

        labEmailCliente.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labEmailCliente.setText("E-mail:");
        panDadosPessoaisCliente.add(labEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        panDadosPessoaisCliente.add(fieldEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 280, -1));

        labCPFCliente.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labCPFCliente.setText("CPF:");
        panDadosPessoaisCliente.add(labCPFCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        try {
            formatCPFCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatCPFClienteActionPerformed(evt);
            }
        });
        panDadosPessoaisCliente.add(formatCPFCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 90, -1));

        labCelularCliente.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labCelularCliente.setText("Celular:");
        panDadosPessoaisCliente.add(labCelularCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        try {
            formatCelularCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatCelularCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatCelularClienteActionPerformed(evt);
            }
        });
        panDadosPessoaisCliente.add(formatCelularCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 90, -1));

        panClientes.add(panDadosPessoaisCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 360, 210));

        panEnderecoCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));
        panEnderecoCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labCEPCliente.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labCEPCliente.setText("CEP:");
        panEnderecoCliente.add(labCEPCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        try {
            formatCEPCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        panEnderecoCliente.add(formatCEPCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));

        labNCliente.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labNCliente.setText("Nº:");
        panEnderecoCliente.add(labNCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        formatNCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        panEnderecoCliente.add(formatNCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 40, -1));

        labCidadeCliente.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labCidadeCliente.setText("Cidade:");
        panEnderecoCliente.add(labCidadeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        panEnderecoCliente.add(fieldCidadeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 90, -1));

        cbEstadoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UF", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        panEnderecoCliente.add(cbEstadoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 50, -1));

        labBairroCliente.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labBairroCliente.setText("Bairro:");
        panEnderecoCliente.add(labBairroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        labComplementoCliente.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labComplementoCliente.setText("Complemento:");
        panEnderecoCliente.add(labComplementoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        labRuaCliente.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labRuaCliente.setText("Rua:");
        panEnderecoCliente.add(labRuaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        panEnderecoCliente.add(fieldRuaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 170, -1));
        panEnderecoCliente.add(fieldComplementoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 110, -1));
        panEnderecoCliente.add(fieldBairroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 160, -1));

        panClientes.add(panEnderecoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 230, 210));

        tpanMenu.addTab("Clientes", panClientes);

        panProduto.setForeground(new java.awt.Color(102, 51, 0));
        panProduto.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        panProduto.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N

        panConsultarProduto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btEditarConsultarProduto.setText("Editar");
        panConsultarProduto.add(btEditarConsultarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 110, 30));

        btSalvarConsultarProduto.setText("Salvar");
        btSalvarConsultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarConsultarProdutoActionPerformed(evt);
            }
        });
        panConsultarProduto.add(btSalvarConsultarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 110, 30));

        btCancelarConsultarProduto1.setText("Cancelar");
        panConsultarProduto.add(btCancelarConsultarProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, 30));

        btExcluirConsultarProduto.setText("Excluir");
        panConsultarProduto.add(btExcluirConsultarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 110, 30));

        panConsultarProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Produtos"));
        panConsultarProdutos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labDescricaoConsultarProduto.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labDescricaoConsultarProduto.setText("Descrição:");
        panConsultarProdutos.add(labDescricaoConsultarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        panConsultarProdutos.add(fieldDescricaoConsultarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 280, -1));

        btPesquisarConsultarProduto.setText("Buscar");
        panConsultarProdutos.add(btPesquisarConsultarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 70, -1));

        tableConsultarProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome", "Descrição", "Categoria", "Fornecedor", "Qt Estoque", "Tam/Peso", "Unid Medida", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableConsultarProduto);

        panConsultarProdutos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 47, 440, 160));

        panConsultarProduto.add(panConsultarProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 460, 220));
        panConsultarProdutos.getAccessibleContext().setAccessibleName("Consultar Produto");

        panProduto.addTab("Consultar Produtos", panConsultarProduto);

        panControleEstoque.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labDescricaoControle.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labDescricaoControle.setText("Descrição:");
        panControleEstoque.add(labDescricaoControle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        fieldQtAtualControleEstoque.setEditable(false);
        panControleEstoque.add(fieldQtAtualControleEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 40, -1));

        btAdicionarControleEstoque.setText("+");
        btAdicionarControleEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarControleEstoqueActionPerformed(evt);
            }
        });
        panControleEstoque.add(btAdicionarControleEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 40, -1));

        labQtAtualControleEstoque.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labQtAtualControleEstoque.setText("Quantidade Atual:");
        panControleEstoque.add(labQtAtualControleEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        panControleEstoque.add(fieldDescricaoControleEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 310, -1));

        labAdicionarQuantidade.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labAdicionarQuantidade.setText("Adicionar Quantidade:");
        panControleEstoque.add(labAdicionarQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));
        panControleEstoque.add(fieldQtControleEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 50, -1));

        btBuscarProdutoControleEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarProdutoControleEstoqueActionPerformed(evt);
            }
        });
        panControleEstoque.add(btBuscarProdutoControleEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 40, 20));

        panListaProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder("Listar Produtos"));
        panListaProdutos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableControleProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome", "Descrição", "Fornecedor", "Qt Estoque", "Tam/Peso", "Unid Medida", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tableControleProduto);

        panListaProdutos.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 440, 150));

        panControleEstoque.add(panListaProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 460, 190));
        panListaProdutos.getAccessibleContext().setAccessibleName("Lista de Produtos");

        panProduto.addTab("Controle de Estoque", panControleEstoque);

        panCadastrarProduto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btCancelarCadastrarProduto.setText("Cancelar");
        btCancelarCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarCadastrarProdutoActionPerformed(evt);
            }
        });
        panCadastrarProduto.add(btCancelarCadastrarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 110, 30));

        btSalvarCadastrarProduto.setText("Salvar");
        btSalvarCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarCadastrarProdutoActionPerformed(evt);
            }
        });
        panCadastrarProduto.add(btSalvarCadastrarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 110, 30));

        panCadastrarProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Produtos"));
        panCadastrarProdutos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labFornecedorProduto.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labFornecedorProduto.setText("Fornecedor:");
        panCadastrarProdutos.add(labFornecedorProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        labQtEstoqueProduto.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labQtEstoqueProduto.setText("Qt. estoque:");
        panCadastrarProdutos.add(labQtEstoqueProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        labDescricaoProduto.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labDescricaoProduto.setText("Descrição:");
        panCadastrarProdutos.add(labDescricaoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        labNomeProduto.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labNomeProduto.setText("Nome:");
        panCadastrarProdutos.add(labNomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        labCodigoProduto.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labCodigoProduto.setText("Código:");
        panCadastrarProdutos.add(labCodigoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        fieldCodigoProduto1.setEditable(false);
        panCadastrarProdutos.add(fieldCodigoProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 40, -1));

        cbUnidadeMedidaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unid Medida", "g", "kg", "ml", " " }));
        panCadastrarProdutos.add(cbUnidadeMedidaProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 50, -1));

        formatTamProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        panCadastrarProdutos.add(formatTamProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 60, -1));

        labTamProduto.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labTamProduto.setText("Tam/Pes:");
        panCadastrarProdutos.add(labTamProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));
        panCadastrarProdutos.add(fieldNomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 250, -1));
        panCadastrarProdutos.add(fieldDescricaoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 250, -1));

        formatQtEstoqueProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        panCadastrarProdutos.add(formatQtEstoqueProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 50, -1));

        labPrecoProduto.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labPrecoProduto.setText("Preço Unid:");
        panCadastrarProdutos.add(labPrecoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        formatPrecoProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        panCadastrarProdutos.add(formatPrecoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 60, -1));

        cbCategoriaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria", "Café", "Chá", "Bebida", "Salgado", "Bolo", "Pão", " ", " " }));
        panCadastrarProdutos.add(cbCategoriaProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 90, -1));

        panCadastrarProdutos.add(cbFornecedorProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 140, -1));

        panCadastrarProduto.add(panCadastrarProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 420, 200));
        panCadastrarProdutos.getAccessibleContext().setAccessibleName("Cadastrar");

        panProduto.addTab("Cadastrar Produtos", panCadastrarProduto);

        tpanMenu.addTab("Produtos", panProduto);

        panVenda.setForeground(new java.awt.Color(102, 51, 0));
        panVenda.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        panVenda.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N

        panPontoVenda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btAdicionarProdutoVenda.setText("Adicionar produto");
        btAdicionarProdutoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarProdutoVendaActionPerformed(evt);
            }
        });
        panPontoVenda.add(btAdicionarProdutoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        btLimparDadosVenda.setText("Limpar dados");
        btLimparDadosVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparDadosVendaActionPerformed(evt);
            }
        });
        panPontoVenda.add(btLimparDadosVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        panDadosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cliente"));
        panDadosCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labCPFClienteVenda.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labCPFClienteVenda.setText("CPF:");
        panDadosCliente.add(labCPFClienteVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        try {
            formatCPFClienteVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        panDadosCliente.add(formatCPFClienteVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 100, -1));

        labNomeClienteVenda.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labNomeClienteVenda.setText("Nome:");
        panDadosCliente.add(labNomeClienteVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        panDadosCliente.add(fieldNomeClienteVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 210, -1));

        btBuscarClienteVenda.setText("Buscar");
        panDadosCliente.add(btBuscarClienteVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 70, -1));

        panPontoVenda.add(panDadosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 90));

        panDadosProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Produto"));
        panDadosProduto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labCodigoProdutoVenda.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labCodigoProdutoVenda.setText("Código:");
        panDadosProduto.add(labCodigoProdutoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        panDadosProduto.add(fieldCodigoProdutoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, -1));

        btBuscarProdutoVenda.setText("Buscar");
        panDadosProduto.add(btBuscarProdutoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 70, -1));

        labNomeProdutoVenda.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labNomeProdutoVenda.setText("Nome:");
        panDadosProduto.add(labNomeProdutoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        panDadosProduto.add(fieldNomeProdutoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 190, -1));

        labEstoqueProdutoVenda.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labEstoqueProdutoVenda.setText("Estoque:");
        panDadosProduto.add(labEstoqueProdutoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        formatEstoqueProdutoVenda.setEditable(false);
        formatEstoqueProdutoVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        panDadosProduto.add(formatEstoqueProdutoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 50, -1));

        labQtProdutoVenda.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labQtProdutoVenda.setText("Qt:");
        panDadosProduto.add(labQtProdutoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        formatQtProdutoVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        panDadosProduto.add(formatQtProdutoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 50, -1));

        formatDescontoProdutoVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0%"))));
        panDadosProduto.add(formatDescontoProdutoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 50, -1));

        labDescontoProdutoVenda.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labDescontoProdutoVenda.setText("Desconto %:");
        panDadosProduto.add(labDescontoProdutoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        formatPrecoProdutoVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        panDadosProduto.add(formatPrecoProdutoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 50, -1));

        labPrecoProdutoVenda.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labPrecoProdutoVenda.setText("Preço:");
        panDadosProduto.add(labPrecoProdutoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        panPontoVenda.add(panDadosProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 280, 150));

        panCarrinho.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrinho"));
        panCarrinho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formatTotalCarrinhoVenda.setBorder(null);
        formatTotalCarrinhoVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        formatTotalCarrinhoVenda.setText("0,00");
        panCarrinho.add(formatTotalCarrinhoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 60, 20));

        labTotalCarrinhoVenda.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labTotalCarrinhoVenda.setText("Total:");
        panCarrinho.add(labTotalCarrinhoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        btPagamentoCarrinhoVenda.setBackground(new java.awt.Color(51, 204, 255));
        btPagamentoCarrinhoVenda.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btPagamentoCarrinhoVenda.setText("Pagamento");
        panCarrinho.add(btPagamentoCarrinhoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 90, 30));

        fieldDataCarrinhoVenda.setEditable(false);
        panCarrinho.add(fieldDataCarrinhoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 130, -1));

        btCancelarCarrinhoVenda.setText("Cancelar");
        panCarrinho.add(btCancelarCarrinhoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, 30));

        tableCarrinhoVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Qt", "Preco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableCarrinhoVenda);

        panCarrinho.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 151));

        labDataCarrinhoVenda.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labDataCarrinhoVenda.setText("Data:");
        panCarrinho.add(labDataCarrinhoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        panPontoVenda.add(panCarrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 200, 280));

        panVenda.addTab("Ponto de Venda", panPontoVenda);

        panPosicaoDiaVenda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panPosicaoDia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labTotalPosicaoVenda.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        labTotalPosicaoVenda.setText("Total:");
        panPosicaoDia.add(labTotalPosicaoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 70, -1));

        try {
            formatDataPosicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatDataPosicao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panPosicaoDia.add(formatDataPosicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, 40));

        btBuscarPosicaoVenda.setText("Buscar");
        btBuscarPosicaoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPosicaoVendaActionPerformed(evt);
            }
        });
        panPosicaoDia.add(btBuscarPosicaoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 80, 40));
        panPosicaoDia.add(fieldTotalPosicaoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 160, 30));

        labDataPosicaoVenda.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        labDataPosicaoVenda.setText("Data:");
        panPosicaoDia.add(labDataPosicaoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 60, -1));

        panPosicaoDiaVenda.add(panPosicaoDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 350, 150));

        panVenda.addTab("Posição do dia", panPosicaoDiaVenda);

        panHistoricoVenda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panHistorico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labDataFimVenda.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labDataFimVenda.setText("Data fim:");
        panHistorico.add(labDataFimVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 60, -1));

        labDataInicioVenda.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        labDataInicioVenda.setText("Data início:");
        panHistorico.add(labDataInicioVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        try {
            formatDataInicioVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatDataInicioVenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panHistorico.add(formatDataInicioVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 80, 30));

        try {
            formatDataFimVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatDataFimVenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panHistorico.add(formatDataFimVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 80, 30));

        btBuscarHistoricoVenda.setText("Buscar");
        btBuscarHistoricoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarHistoricoVendaActionPerformed(evt);
            }
        });
        panHistorico.add(btBuscarHistoricoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 70, 30));

        tableHistoricoVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF Cliente", "Nome Cliente", "Produto", "Preco"
            }
        ));
        jScrollPane3.setViewportView(tableHistoricoVenda);

        panHistorico.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 57, 420, 210));

        panHistoricoVenda.add(panHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 450, 270));

        panVenda.addTab("Histórico de Vendas", panHistoricoVenda);

        tpanMenu.addTab("Vendas", panVenda);

        javax.swing.GroupLayout panConfiguracaoLayout = new javax.swing.GroupLayout(panConfiguracao);
        panConfiguracao.setLayout(panConfiguracaoLayout);
        panConfiguracaoLayout.setHorizontalGroup(
            panConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        panConfiguracaoLayout.setVerticalGroup(
            panConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        tpanMenu.addTab("Configuração", panConfiguracao);

        panSair.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btEncerrar.setBackground(new java.awt.Color(204, 204, 204));
        btEncerrar.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btEncerrar.setText("ENCERRAR APLICAÇÃO");
        btEncerrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btEncerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btEncerrarMouseClicked(evt);
            }
        });
        btEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEncerrarActionPerformed(evt);
            }
        });
        panSair.add(btEncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 250, 90));

        tpanMenu.addTab("Sair", panSair);

        getContentPane().add(tpanMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 650, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarFornecedorActionPerformed
        // Torna DlgMenu invisivel
        this.setVisible(false);

        try {
            /*Abrir DlgConsultarFornecedor*/
            gInterface.abrirJanelaDlgConsultarFornecedor();
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(DlgMenu.class.getName()).log(Level.SEVERE, null, ex);            
            JOptionPane.showMessageDialog(this, "Erro ao abrir a janela Consultar Fornecedor", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btConsultarFornecedorActionPerformed

    private void btCancelarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarFornecedorActionPerformed
        limparCamposFornecedor();
    }//GEN-LAST:event_btCancelarFornecedorActionPerformed

    private void btSalvarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarFornecedorActionPerformed

        if(validarCamposFornecedor()){
            String nome = fieldNomeFornecedor.getText(),
                    cnpj = formatCNPJFornecedor.getText(),
                    email = fieldEmailFornecedor.getText(),
                    celular = formatCelularFornecedor.getText(),
                    cep = formatCEPFornecedor.getText(),
                    estado = String.valueOf(cbEstadoFornecedor.getSelectedItem()),
                    cidade = fieldCidadeFornecedor.getText(),
                    bairro = fieldBairroFornecedor.getText(),
                    complemento = fieldComplementoFornecedor.getText(),
                    rua = fieldRuaFornecedor.getText();
            int numero = Integer.parseInt(formatNFornecedor.getText());

            
            try{
                Fornecedor fornecedor = GerenciadorDeInterface.getInstance().getDominio().inserirFornecedor(cnpj, nome, email, celular, cep, bairro, numero, complemento, rua, cidade, estado);
                
                /*Dados salvos*/
                dadosSalvos();
                JOptionPane.showMessageDialog(this, "Fornecedor" + fornecedor.getIdPessoa() + "inserido com sucesso.", "Cadastro Fornecedor", JOptionPane.INFORMATION_MESSAGE);
                
                /*limpar campos*/
                limparCamposFornecedor();
                
            }catch(HibernateException ex){
                JOptionPane.showMessageDialog(this, "Erro nos dados: " + ex.getMessage(), "ERRO Cadastro Fornecedor", JOptionPane.ERROR_MESSAGE);
            }            
        }
        
    }//GEN-LAST:event_btSalvarFornecedorActionPerformed

    private void btSalvarConsultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarConsultarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSalvarConsultarProdutoActionPerformed

    private void btAdicionarControleEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarControleEstoqueActionPerformed

    }//GEN-LAST:event_btAdicionarControleEstoqueActionPerformed

    private void btBuscarProdutoControleEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarProdutoControleEstoqueActionPerformed

    }//GEN-LAST:event_btBuscarProdutoControleEstoqueActionPerformed

    private void btCancelarCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarCadastrarProdutoActionPerformed

        fieldNomeProduto.setText("");
        fieldDescricaoProduto.setText("");
        formatQtEstoqueProduto.setText("");
        formatPrecoProduto.setText("");
        formatTamProduto.setText("");

        cbUnidadeMedidaProduto.setSelectedIndex(0);
        cbCategoriaProduto.setSelectedIndex(0);

        if(cbFornecedorProduto.getItemCount() > 0){
            cbFornecedorProduto.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btCancelarCadastrarProdutoActionPerformed

    private void btSalvarCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarCadastrarProdutoActionPerformed

        if(validarCamposProduto()){

            String nome = fieldNomeProduto.getText(),
                    unidMedida = (String) cbUnidadeMedidaProduto.getSelectedItem(),
                    categoria = (String) cbCategoriaProduto.getSelectedItem();
            
            double valor = Double.parseDouble(formatPrecoProduto.getText().replace(',', '.')),
                    tam_pes = Double.parseDouble(formatTamProduto.getText().replace(',', '.'));

            Produto produto = new Produto(nome, valor, tam_pes, unidMedida, categoria);

            //Aviso de sucesso
            dadosSalvos();

            /*Adicionar na tabela produto*/

        }
    }//GEN-LAST:event_btSalvarCadastrarProdutoActionPerformed

    private void btSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarClienteActionPerformed
        
        if(validarCamposCliente()){
            String nome = fieldNomeCliente.getText(),
                    cpf = formatCPFCliente.getText(),
                    email = fieldEmailCliente.getText(),
                    celular = formatCelularCliente.getText(),
                    cep = formatCEPCliente.getText(),
                    estado = String.valueOf(cbEstadoCliente.getSelectedItem()),
                    cidade = fieldCidadeCliente.getText(),
                    bairro = fieldBairroCliente.getText(),
                    complemento = fieldComplementoCliente.getText(),
                    rua = fieldRuaCliente.getText();
            int numero = Integer.parseInt(formatNCliente.getText());

            try{
                Cliente cliente = GerenciadorDeInterface.getInstance().getDominio().inserirCliente(cpf, nome, email, celular, cep, bairro, numero, complemento, rua, cidade, estado);
                
                /*Dados salvos*/
                dadosSalvos();
                JOptionPane.showMessageDialog(this, "Cliente" + cliente.getIdPessoa() + "inserido com sucesso.", "Cadastro Cliente", JOptionPane.INFORMATION_MESSAGE);
                
                /*limpar campos*/
                limparCamposCliente();
                
            }catch(HibernateException ex){
                JOptionPane.showMessageDialog(this, "Erro nos dados: " + ex.getMessage(), "ERRO Cadastro Cliente", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btSalvarClienteActionPerformed

    private void btCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarClienteActionPerformed
        // TODO add your handling code here:
        limparCamposCliente();
    }//GEN-LAST:event_btCancelarClienteActionPerformed

    private void btConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarClienteActionPerformed
        // Torna DlgMenu invisivel
        this.setVisible(false);

        try {
            //Abre DlgConsultarCliente
            gInterface.abrirJanelaDlgConsultarCliente();
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(DlgMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btConsultarClienteActionPerformed

    private void btAdicionarProdutoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarProdutoVendaActionPerformed

        if(validarCamposVenda()){

            String cpfCli = formatCPFClienteVenda.getText(),
            nomeCli = fieldNomeClienteVenda.getText(),
            nomePro = fieldNomeProdutoVenda.getText();

            /* String para Date*/
            Date dataVenda = null;
            Date hora = null;
            try {
                dataVenda = strToDate(fieldDataCarrinhoVenda.getText());
                hora = strToDate(fieldDataCarrinhoVenda.getText());
            } catch (ParseException ex) {
                Logger.getLogger(DlgMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            double totalVenda = Double.parseDouble(formatTotalCarrinhoVenda.getText());

            
            try{
                Venda venda = GerenciadorDeInterface.getInstance().getDominio().inserirVendas(dataVenda, totalVenda, hora);
                
                /*Dados salvos*/
                dadosSalvos();
                JOptionPane.showMessageDialog(this, "Venda" + venda.getIdVenda() + "inserido com sucesso.", "Cadastro Venda", JOptionPane.INFORMATION_MESSAGE);
                
                /*limpar campos*/
                limparCamposVenda();
                
            }catch(HibernateException ex){
                JOptionPane.showMessageDialog(this, "Erro nos dados" + ex.getMessage(), "ERRO Cadastro Venda", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btAdicionarProdutoVendaActionPerformed

    private void btLimparDadosVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparDadosVendaActionPerformed
        fieldCodigoProdutoVenda.setText("");
        formatQtProdutoVenda.setText("");
        formatDescontoProdutoVenda.setText("");
        formatCPFClienteVenda.setText("");
        fieldNomeClienteVenda.setText("");
        fieldNomeProdutoVenda.setText("");
    }//GEN-LAST:event_btLimparDadosVendaActionPerformed

    private void btBuscarPosicaoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPosicaoVendaActionPerformed

    }//GEN-LAST:event_btBuscarPosicaoVendaActionPerformed

    private void btBuscarHistoricoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarHistoricoVendaActionPerformed

    }//GEN-LAST:event_btBuscarHistoricoVendaActionPerformed

    private void btEncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEncerrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btEncerrarMouseClicked

    private void btEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEncerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btEncerrarActionPerformed

    private void formatCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatCPFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatCPFClienteActionPerformed

    private void formatCelularClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatCelularClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatCelularClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarControleEstoque;
    private javax.swing.JButton btAdicionarProdutoVenda;
    private javax.swing.JToggleButton btBuscarClienteVenda;
    private javax.swing.JButton btBuscarHistoricoVenda;
    private javax.swing.JButton btBuscarPosicaoVenda;
    private javax.swing.JButton btBuscarProdutoControleEstoque;
    private javax.swing.JToggleButton btBuscarProdutoVenda;
    private javax.swing.JButton btCancelarCadastrarProduto;
    private javax.swing.JButton btCancelarCarrinhoVenda;
    private javax.swing.JButton btCancelarCliente;
    private javax.swing.JButton btCancelarConsultarProduto1;
    private javax.swing.JButton btCancelarFornecedor;
    private javax.swing.JButton btConsultarCliente;
    private javax.swing.JButton btConsultarFornecedor;
    private javax.swing.JButton btEditarConsultarProduto;
    private javax.swing.JToggleButton btEncerrar;
    private javax.swing.JButton btExcluirConsultarProduto;
    private javax.swing.JButton btLimparDadosVenda;
    private javax.swing.JButton btPagamentoCarrinhoVenda;
    private javax.swing.JButton btPesquisarConsultarProduto;
    private javax.swing.JButton btSalvarCadastrarProduto;
    private javax.swing.JButton btSalvarCliente;
    private javax.swing.JButton btSalvarConsultarProduto;
    private javax.swing.JButton btSalvarFornecedor;
    private javax.swing.JComboBox<String> cbCategoriaProduto;
    private javax.swing.JComboBox<String> cbEstadoCliente;
    private javax.swing.JComboBox<String> cbEstadoFornecedor;
    private javax.swing.JComboBox<String> cbFornecedorProduto;
    private javax.swing.JComboBox<String> cbUnidadeMedidaProduto;
    private javax.swing.JTextField fieldBairroCliente;
    private javax.swing.JTextField fieldBairroFornecedor;
    private javax.swing.JTextField fieldCidadeCliente;
    private javax.swing.JTextField fieldCidadeFornecedor;
    private javax.swing.JTextField fieldCodigoProduto1;
    private javax.swing.JTextField fieldCodigoProdutoVenda;
    private javax.swing.JTextField fieldComplementoCliente;
    private javax.swing.JTextField fieldComplementoFornecedor;
    private javax.swing.JTextField fieldDataCarrinhoVenda;
    private javax.swing.JTextField fieldDescricaoConsultarProduto;
    private javax.swing.JTextField fieldDescricaoControleEstoque;
    private javax.swing.JTextField fieldDescricaoProduto;
    private javax.swing.JTextField fieldEmailCliente;
    private javax.swing.JTextField fieldEmailFornecedor;
    private javax.swing.JTextField fieldNomeCliente;
    private javax.swing.JTextField fieldNomeClienteVenda;
    private javax.swing.JTextField fieldNomeFornecedor;
    private javax.swing.JTextField fieldNomeProduto;
    private javax.swing.JTextField fieldNomeProdutoVenda;
    private javax.swing.JTextField fieldQtAtualControleEstoque;
    private javax.swing.JTextField fieldQtControleEstoque;
    private javax.swing.JTextField fieldRuaCliente;
    private javax.swing.JTextField fieldRuaFornecedor;
    private javax.swing.JTextField fieldTotalPosicaoVenda;
    private javax.swing.JFormattedTextField formatCEPCliente;
    private javax.swing.JFormattedTextField formatCEPFornecedor;
    private javax.swing.JFormattedTextField formatCNPJFornecedor;
    private javax.swing.JFormattedTextField formatCPFCliente;
    private javax.swing.JFormattedTextField formatCPFClienteVenda;
    private javax.swing.JFormattedTextField formatCelularCliente;
    private javax.swing.JFormattedTextField formatCelularFornecedor;
    private javax.swing.JFormattedTextField formatDataFimVenda;
    private javax.swing.JFormattedTextField formatDataInicioVenda;
    private javax.swing.JFormattedTextField formatDataPosicao;
    private javax.swing.JFormattedTextField formatDescontoProdutoVenda;
    private javax.swing.JFormattedTextField formatEstoqueProdutoVenda;
    private javax.swing.JFormattedTextField formatNCliente;
    private javax.swing.JFormattedTextField formatNFornecedor;
    private javax.swing.JFormattedTextField formatPrecoProduto;
    private javax.swing.JFormattedTextField formatPrecoProdutoVenda;
    private javax.swing.JFormattedTextField formatQtEstoqueProduto;
    private javax.swing.JFormattedTextField formatQtProdutoVenda;
    private javax.swing.JFormattedTextField formatTamProduto;
    private javax.swing.JFormattedTextField formatTotalCarrinhoVenda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labAdicionarQuantidade;
    private javax.swing.JLabel labBairroCliente;
    private javax.swing.JLabel labBairroFornecedor;
    private javax.swing.JLabel labCEPCliente;
    private javax.swing.JLabel labCEPFornecedor;
    private javax.swing.JLabel labCNPJFornecedor;
    private javax.swing.JLabel labCPFCliente;
    private javax.swing.JLabel labCPFClienteVenda;
    private javax.swing.JLabel labCelularCliente;
    private javax.swing.JLabel labCelularFornecedor;
    private javax.swing.JLabel labCidadeCliente;
    private javax.swing.JLabel labCidadeFornecedor;
    private javax.swing.JLabel labCodigoProduto;
    private javax.swing.JLabel labCodigoProdutoVenda;
    private javax.swing.JLabel labComplementoCliente;
    private javax.swing.JLabel labComplementoFornecedor;
    private javax.swing.JLabel labDataCarrinhoVenda;
    private javax.swing.JLabel labDataFimVenda;
    private javax.swing.JLabel labDataInicioVenda;
    private javax.swing.JLabel labDataPosicaoVenda;
    private javax.swing.JLabel labDescontoProdutoVenda;
    private javax.swing.JLabel labDescricaoConsultarProduto;
    private javax.swing.JLabel labDescricaoControle;
    private javax.swing.JLabel labDescricaoProduto;
    private javax.swing.JLabel labEmailCliente;
    private javax.swing.JLabel labEmailFornecedor;
    private javax.swing.JLabel labEstoqueProdutoVenda;
    private javax.swing.JLabel labFornecedorProduto;
    private javax.swing.JLabel labNCliente;
    private javax.swing.JLabel labNFornecedor;
    private javax.swing.JLabel labNomeCliente;
    private javax.swing.JLabel labNomeClienteVenda;
    private javax.swing.JLabel labNomeFornecedor;
    private javax.swing.JLabel labNomeProduto;
    private javax.swing.JLabel labNomeProdutoVenda;
    private javax.swing.JLabel labPrecoProduto;
    private javax.swing.JLabel labPrecoProdutoVenda;
    private javax.swing.JLabel labQtAtualControleEstoque;
    private javax.swing.JLabel labQtEstoqueProduto;
    private javax.swing.JLabel labQtProdutoVenda;
    private javax.swing.JLabel labRuaCliente;
    private javax.swing.JLabel labRuaFornecedor;
    private javax.swing.JLabel labTamProduto;
    private javax.swing.JLabel labTotalCarrinhoVenda;
    private javax.swing.JLabel labTotalPosicaoVenda;
    private javax.swing.JPanel panCadastrarProduto;
    private javax.swing.JPanel panCadastrarProdutos;
    private javax.swing.JPanel panCarrinho;
    private javax.swing.JPanel panClientes;
    private javax.swing.JPanel panConfiguracao;
    private javax.swing.JPanel panConsultarProduto;
    private javax.swing.JPanel panConsultarProdutos;
    private javax.swing.JPanel panControleEstoque;
    private javax.swing.JPanel panDadosCliente;
    private javax.swing.JPanel panDadosPessoaisCliente;
    private javax.swing.JPanel panDadosPessoaisFornecedor;
    private javax.swing.JPanel panDadosProduto;
    private javax.swing.JPanel panEnderecoCliente;
    private javax.swing.JPanel panEnderecoFornecedor;
    private javax.swing.JPanel panFornecedor;
    private javax.swing.JPanel panHistorico;
    private javax.swing.JPanel panHistoricoVenda;
    private javax.swing.JPanel panListaProdutos;
    private javax.swing.JPanel panPontoVenda;
    private javax.swing.JPanel panPosicaoDia;
    private javax.swing.JPanel panPosicaoDiaVenda;
    private javax.swing.JTabbedPane panProduto;
    private javax.swing.JPanel panSair;
    private javax.swing.JTabbedPane panVenda;
    private javax.swing.JTable tableCarrinhoVenda;
    private javax.swing.JTable tableConsultarProduto;
    private javax.swing.JTable tableControleProduto;
    private javax.swing.JTable tableHistoricoVenda;
    private javax.swing.JTabbedPane tpanMenu;
    // End of variables declaration//GEN-END:variables
    
    
    
    public void dadosSalvos() {
        JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!");
    }

    
          /*   VALIDAR CAMPOS   */
    
    
    
    
    /*  VALIDAR CAMPOS FORNECEDOR  */
    
    
    private boolean validarCamposFornecedor() {
        String msgErro = "";
        
        labNomeFornecedor.setForeground(Color.black);
        labEmailFornecedor.setForeground(Color.black);
        labCelularFornecedor.setForeground(Color.black);
        labCNPJFornecedor.setForeground(Color.black);
        labCEPFornecedor.setForeground(Color.black);
        labCidadeFornecedor.setForeground(Color.black);
        labBairroFornecedor.setForeground(Color.black); 
        labNFornecedor.setForeground(Color.black);
        
                
        if(cbEstadoFornecedor.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Digite UF válido!");
            return false;
        }
        
        if(fieldNomeFornecedor.getText().isEmpty()){
            msgErro = msgErro + "Adicione um nome.\n";
            labNomeFornecedor.setForeground(Color.red); 
        }
        
        if(fieldEmailFornecedor.getText().isEmpty()){
            msgErro = msgErro + "Adicione um email.\n";
            labEmailFornecedor.setForeground(Color.red); 
        }
        
        if(formatCelularFornecedor.getValue() == null){
            msgErro = msgErro + "Adicione um celular.\n";
            labCelularFornecedor.setForeground(Color.red); 
        }
        
        if(formatCNPJFornecedor.getValue() == null){
            msgErro = msgErro + "Adicione um CNPJ.\n";
            labCNPJFornecedor.setForeground(Color.red); 
        }
        
        if(formatCEPFornecedor.getValue() == null){
            msgErro = msgErro + "Adicione um CEP.\n";
            labCEPFornecedor.setForeground(Color.red); 
        }
        
        if(fieldCidadeFornecedor.getText().isEmpty()){
            msgErro = msgErro + "Adicione uma cidade.\n";
            labCidadeFornecedor.setForeground(Color.red); 
        }
        
        if(fieldBairroFornecedor.getText().isEmpty()){
            msgErro = msgErro + "Adicione um bairro.\n";
            labBairroFornecedor.setForeground(Color.red); 
        }
        
        if(formatNFornecedor.getText().isEmpty()){
            msgErro = msgErro + "Adicione um número.\n";
            labNFornecedor.setForeground(Color.red);
        }  
        
        if ( msgErro.isEmpty() ) {
            return true;
        } else {            
            JOptionPane.showMessageDialog(this, msgErro, "ERRO Fornecedor", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }    
    
    
    /*  VALIDAR CAMPOS PRODUTO  */
    
    
    private boolean validarCamposProduto() {
        String msgErro = "";
        
        labNomeProduto.setForeground(Color.black);
        labDescricaoProduto.setForeground(Color.black);
        labPrecoProduto.setForeground(Color.black);
        labQtEstoqueProduto.setForeground(Color.black);
        labTamProduto.setForeground(Color.black);
          
        if(cbUnidadeMedidaProduto.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Digite Unidade de Medida válida!");
            return false;
        }
        
        if(cbCategoriaProduto.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Digite categoria válida!");
            return false;
        }
                
        if(fieldNomeProduto.getText().isEmpty()){
            msgErro = msgErro + "Adicione um nome.\n";
            labNomeProduto.setForeground(Color.red); 
        }
        
        if(fieldDescricaoProduto.getText().isEmpty()){
            msgErro = msgErro + "Adicione uma descrição.\n";
            labDescricaoProduto.setForeground(Color.red); 
        }
        
        if(formatPrecoProduto.getText().isEmpty()){
            msgErro = msgErro + "Adicione um preço.\n";
            labPrecoProduto.setForeground(Color.red); 
        }
        
        if(formatQtEstoqueProduto.getText().isEmpty()){
            msgErro = msgErro + "Adicione um quantidade de estoque.\n";
            labQtEstoqueProduto.setForeground(Color.red); 
        }
        
        if(formatTamProduto.getText().isEmpty()){
            msgErro = msgErro + "Adicione uma tamanho/ peso.\n";
            labTamProduto.setForeground(Color.red); 
        }
        
        if ( msgErro.isEmpty() ) {
            return true;
        } else {            
            JOptionPane.showMessageDialog(this, msgErro, "ERRO Produto", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    
    /*  VALIDAR CAMPOS CLIENTE  */
    
    
    private boolean validarCamposCliente() {
        String msgErro = "";
        
        labCPFCliente.setForeground(Color.black);
        labNomeCliente.setForeground(Color.black);
        labEmailCliente.setForeground(Color.black);
        labCelularCliente.setForeground(Color.black);
        
        labCEPCliente.setForeground(Color.black);
        labBairroCliente.setForeground(Color.black);
        formatNCliente.setForeground(Color.black);
        labComplementoCliente.setForeground(Color.black);
        labCidadeCliente.setForeground(Color.black);
        
        if(cbEstadoCliente.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Digite UF válido!");
            return false;
        }
        
        if(formatCPFCliente.getValue() == null){
            msgErro = msgErro + "Adicione um CNPJ.\n";
            labCPFCliente.setForeground(Color.red); 
        }
        
        if(fieldNomeCliente.getText().isEmpty()){
            msgErro = msgErro + "Adicione um nome.\n";
            labNomeCliente.setForeground(Color.red); 
        }
        
        if(fieldEmailCliente.getText().isEmpty()){
            msgErro = msgErro + "Adicione um email.\n";
            labEmailCliente.setForeground(Color.red); 
        }
        
        if(formatCelularCliente.getValue() == null){
            msgErro = msgErro + "Adicione um celular.\n";
            labCelularCliente.setForeground(Color.red); 
        }
        
        
        if(formatCEPCliente.getValue() == null){
            msgErro = msgErro + "Adicione um CEP.\n";
            labCEPCliente.setForeground(Color.red); 
        }
        
        if(fieldBairroCliente.getText().isEmpty()){
            msgErro = msgErro + "Adicione um bairro.\n";
            labBairroCliente.setForeground(Color.red); 
        } 
        
        if(formatNCliente.getText().isEmpty()){
            msgErro = msgErro + "Adicione um bairro.\n";
            labNCliente.setForeground(Color.red); 
        }
        
        if(fieldCidadeCliente.getText().isEmpty()){
            msgErro = msgErro + "Adicione uma cidade.\n";
            labCidadeCliente.setForeground(Color.red); 
        }
                
        if ( msgErro.isEmpty() ) {
            return true;
        } else {            
            JOptionPane.showMessageDialog(this, msgErro, "ERRO Cliente", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    /*  VALIDAR CAMPOS VENDA  */
    
    private boolean validarCamposVenda() {
        String msgErro = "";
        
        labCPFClienteVenda.setForeground(Color.black);
        labCodigoProdutoVenda.setForeground(Color.black);
        labQtProdutoVenda.setForeground(Color.black);
        
        if(formatCPFClienteVenda.getValue() == null){
            msgErro = msgErro + "Adicione um CPF.\n";
            labCPFClienteVenda.setForeground(Color.red);
        }
        
        if(fieldCodigoProdutoVenda.getText().isEmpty()){
            msgErro = msgErro + "Adicione um Código.\n";
            labCodigoProdutoVenda.setForeground(Color.red);
        }
        
        if(formatQtProdutoVenda.getValue() == null){
            msgErro = msgErro + "Adicione uma quantidade.\n";
            labQtProdutoVenda.setForeground(Color.red);
        }
        
        if ( msgErro.isEmpty() ) {
            return true;
        } else {            
            JOptionPane.showMessageDialog(this, msgErro, "ERRO Venda", JOptionPane.ERROR_MESSAGE);
            return false;
        }        
    }
    
    /* LIMPAR CAMPOS */
    public void limparCamposFornecedor(){
        formatCNPJFornecedor.setText("");
        fieldNomeFornecedor.setText("");
        fieldEmailFornecedor.setText("");        
        formatCelularFornecedor.setText("");

        formatCEPFornecedor.setText("");
        fieldBairroFornecedor.setText("");
        formatNFornecedor.setText("");
        fieldCidadeFornecedor.setText("");
        fieldComplementoFornecedor.setText("");
        fieldRuaFornecedor.setText("");

        if(cbEstadoFornecedor.getItemCount() > 0){
            cbEstadoFornecedor.setSelectedIndex(0);
        }
    }
    
    public void limparCamposCliente(){
        formatCPFCliente.setText("");
        fieldNomeCliente.setText("");
        fieldEmailCliente.setText("");        
        formatCelularCliente.setText("");

        formatCEPCliente.setText("");
        fieldBairroCliente.setText("");
        formatNCliente.setText("");
        fieldCidadeCliente.setText("");
        fieldComplementoCliente.setText("");
        fieldRuaCliente.setText("");

        if(cbEstadoCliente.getItemCount() > 0){
            cbEstadoCliente.setSelectedIndex(0);
        }
    }
    
    public void limparCamposVenda(){
        
    }
    
    /*  CONVERT STRING PARA DATE   */
    
    public static Date strToDate( String strDt) throws ParseException {
        DateFormat dtForm = new SimpleDateFormat("dd/MM/yyyy");
        dtForm.setLenient(false);
        return dtForm.parse(strDt);
    }
    
    /*  CONVERT DATE PARA STRING   */
    
    public static String dateToStr( Date dt) throws ParseException {
        DateFormat dtForm = new SimpleDateFormat("dd/MM/yyyy");
        dtForm.setLenient(false);
        return dtForm.format(dt);
    }

}